DROP SEQUENCE SEQ_MANAGER;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_RECEIPT_PROCESSING;
DROP SEQUENCE SEQ_RECEIPT_PROCESSING_STATE;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_CARD;
DROP SEQUENCE SEQ_CARD_COMPANY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_MEMO;
DROP SEQUENCE SEQ_RECEIPT_APPLICATION;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_RECEIPT;

CREATE SEQUENCE SEQ_MANAGER                     NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MEMBER                      NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RECEIPT_PROCESSING          NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RECEIPT_PROCESSING_STATE    NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY                    NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CARD                        NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CARD_COMPANY                NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_NOTICE                      NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_FAQ                         NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT                     NOCYCLE NOCACHE ;
CREATE SEQUENCE SEQ_MEMO                        NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RECEIPT_APPLICATION         NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MESSAGE                     NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RECEIPT                     NOCYCLE NOCACHE; 

DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE RECEIPT_PROCESSING_HISTORY;
DROP TABLE RECEIPT_APPLICATION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE RECEIPT CASCADE CONSTRAINTS;
DROP TABLE CARD;
DROP TABLE NOTICE;
DROP TABLE FAQ;
DROP TABLE CARD_COMPANY;
DROP TABLE RECEIPT_PROCESSING_STATE CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT;
DROP TABLE MEMO;
DROP TABLE CATEGORY;

--MEMBER----------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE MEMBER(
    NO          NUMBER          PRIMARY KEY NOT NULL
    ,NAME       VARCHAR2(100)   NOT NULL
    ,ID         VARCHAR2(25)    NOT NULL
    ,PWD        VARCHAR2(25)    NOT NULL
    ,QUIT_YN    CHAR(1)         DEFAULT 'N' NOT NULL
    ,PHONE      CHAR(13)        NOT NULL
)
;

INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '안윤진', 'bluejeans', 'in!030901@', '010-1537-9482');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '이엉지', 'twozero', '!qwert1234', '010-1943-4685');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '이은자', 'silver92', 'ddw%8135934', '010-8975-4893');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '마마', 'mimi95', 'rlaalgus@%1', '010-5193-6123');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '황예자', 'itzycake', 'road!%@18935', '010-1537-5193');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '최언준', 'feeling', 'ewoji#!819498', '010-4388-5123');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '김태영', 'slowdancing', '@@981fjosd', '010-6158-8434');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '이찬형', 'akmuold', '@@819awnio', '010-1952-4983');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '이수형', 'akmuyoung', 'afew984!', '010-1988-4987');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '진정국', '3seven', 'fiwoj@8198', '010-1568-8456');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '김제너', 'pinkblack', '846auif@', '010-1598-4987');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '정원영', 'ivevictory', '!asvd48654', '010-9548-6435');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '만지', 'mjeans', 'ia4981@', '010-9519-8454');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '정소미', 'fastforward', '498gameplan#', '010-9483-4948');
INSERT INTO MEMBER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MEMBER.NEXTVAL, '이영웅', 'hero10', 'dod198!85', '010-9984-6156');

----------------------------------------------------------------------------------------------------------------------------------------------------------------------



--MANAGER-------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE MANAGER(
    NO          NUMBER          PRIMARY KEY NOT NULL
    ,NAME       VARCHAR2(100)   NOT NULL
    ,ID         VARCHAR2(25)    NOT NULL
    ,PWD        VARCHAR2(25)    NOT NULL
    ,EXPIRED_YN CHAR(1)         DEFAULT 'N' NOT NULL
    ,PHONE      CHAR(13)        NOT NULL
)
;
INSERT INTO MANAGER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MANAGER.NEXTVAL, '윤허', 'pwd486', '486@dbsgk', '010-4864-8648');
INSERT INTO MANAGER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MANAGER.NEXTVAL, '감채원', 'antifragile94', '502!il1029', '010-9801-9498');
INSERT INTO MANAGER(NO, NAME, ID, PWD, PHONE) VALUES(SEQ_MANAGER.NEXTVAL, '캬리나', '97aespa', 'wef@%189', '010-5918-1978');

----------------------------------------------------------------------------------------------------------------------------------------------------------------------



--CATEGORY-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CATEGORY (
	NO	NUMBER		  PRIMARY KEY      NOT NULL,
	CATEGORY_NAME	VARCHAR2(15)		NOT NULL
);
COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS '식비, 교통, 특별비, 비품,기타';

INSERT INTO CATEGORY(NO, CATEGORY_NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '식비');
INSERT INTO CATEGORY(NO, CATEGORY_NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '교통비');
INSERT INTO CATEGORY(NO, CATEGORY_NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '특별비');
INSERT INTO CATEGORY(NO, CATEGORY_NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '비품');
INSERT INTO CATEGORY(NO, CATEGORY_NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




--RECEIPT_PROCESSING_STATE-------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE RECEIPT_PROCESSING_STATE (
	NO	NUMBER		     NOT NULL PRIMARY KEY,
	RECEIPT_STATE	VARCHAR2(20)	DEFAULT '상신필요' NOT NULL
);

COMMENT ON COLUMN RECEIPT_PROCESSING_STATE.RECEIPT_STATE IS '상신필요,승인중,반려,승인됨';
INSERT INTO RECEIPT_PROCESSING_STATE(NO, RECEIPT_STATE) VALUES (SEQ_RECEIPT_PROCESSING_STATE.NEXTVAL, '상신필요');
INSERT INTO RECEIPT_PROCESSING_STATE(NO, RECEIPT_STATE) VALUES (SEQ_RECEIPT_PROCESSING_STATE.NEXTVAL, '승인중');
INSERT INTO RECEIPT_PROCESSING_STATE(NO, RECEIPT_STATE) VALUES (SEQ_RECEIPT_PROCESSING_STATE.NEXTVAL, '반려');
INSERT INTO RECEIPT_PROCESSING_STATE(NO, RECEIPT_STATE) VALUES (SEQ_RECEIPT_PROCESSING_STATE.NEXTVAL, '승인됨');
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



--RECEIPT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE RECEIPT(
    NO                         NUMBER       NOT NULL   PRIMARY KEY,
    MEMBER_NO                          NUMBER       NOT NULL,
    RECEIPT_PROCESSING_STATE_NO        NUMBER       NOT NULL,
    CATEGORY_NO                        NUMBER       NOT NULL,
    RECEIPT_SERIAL                      VARCHAR2(50) NOT NULL,
    PAYMENT_DATE                        TIMESTAMP    DEFAULT    SYSDATE,
    VENDOR                              VARCHAR2(50) NOT NULL,
    DEL_YN                              CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE RECEIPT ADD CONSTRAINT FK_RECEIPT_MEMBER FOREIGN KEY(MEMBER_NO) references MEMBER(NO);
ALTER TABLE RECEIPT ADD CONSTRAINT FK_RECEIPT_RECEIPT_PROCESSING_STATE FOREIGN KEY(RECEIPT_PROCESSING_STATE_NO) REFERENCES RECEIPT_PROCESSING_STATE(NO);
ALTER TABLE RECEIPT ADD CONSTRAINT FK_RECEIPT_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO);

INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,1,4,1,1125451581512625,TO_TIMESTAMP('2023-10-01','YYYY-MM-DD'),'CU강서구점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,1,4,4,1259876320014623,TO_TIMESTAMP('2023-10-01','YYYY-MM-DD'),'다이소 서초점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,2,4,2,7184699948711262,TO_TIMESTAMP('2023-10-02','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,2,4,5,8184799918711662,TO_TIMESTAMP('2023-10-03','YYYY-MM-DD'),'암소한우 역삼점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,3,4,2,4184998913712661,TO_TIMESTAMP('2023-10-04','YYYY-MM-DD'),'성남종합버스터미널');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,3,3,3,3187996912713621,TO_TIMESTAMP('2023-10-05','YYYY-MM-DD'),'늘바른약국');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,4,4,5,2127992912223622,TO_TIMESTAMP('2023-10-06','YYYY-MM-DD'),'서산인력');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,4,4,3,8127892988223828,TO_TIMESTAMP('2023-10-07','YYYY-MM-DD'),'CU강서구점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,5,4,1,9259979390019623,TO_TIMESTAMP('2023-10-08','YYYY-MM-DD'),'바나프레소 역삼점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,5,4,2,5184599518515565,TO_TIMESTAMP('2023-10-09','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,11,4,2,5205822948204867,TO_TIMESTAMP('2023-10-12','YYYY-MM-DD'),'성남종합버스터미널');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,11,4,1,3849682738594918,TO_TIMESTAMP('2023-10-12','YYYY-MM-DD'),'GS성남터미널점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,12,4,2,1948692840296725,TO_TIMESTAMP('2023-10-13','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,12,4,5,2364373948771936,TO_TIMESTAMP('2023-10-14','YYYY-MM-DD'),'야누스곱창');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,13,4,4,1038594820128948,TO_TIMESTAMP('2023-10-14','YYYY-MM-DD'),'다이소 서초점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,13,3,3,7294869385979392,TO_TIMESTAMP('2023-10-16','YYYY-MM-DD'),'강남행복약국');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,14,4,1,1937596859306087,TO_TIMESTAMP('2023-10-17','YYYY-MM-DD'),'CU강서구점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,14,4,2,2938571093850912,TO_TIMESTAMP('2023-10-20','YYYY-MM-DD'),'GS칼텍스 하남점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,15,3,2,1849784729496727,TO_TIMESTAMP('2023-10-21','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,15,2,4,3587727593089027,TO_TIMESTAMP('2023-10-22','YYYY-MM-DD'),'다이소 서초점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,6,2,1,6678134569251746,TO_TIMESTAMP('2023-10-23','YYYY-MM-DD'),'메가커피 역삼테헤란로점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,6,2,1,6139526471876576,TO_TIMESTAMP('2023-10-23','YYYY-MM-DD'),'이층맥주창고');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,7,2,1,7184623148756862,TO_TIMESTAMP('2023-10-24','YYYY-MM-DD'),'세븐일레븐 역삼은탑점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,7,2,1,1564848765131568,TO_TIMESTAMP('2023-10-24','YYYY-MM-DD'),'역삼갈비');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,8,2,1,7896543216546489,TO_TIMESTAMP('2023-10-25','YYYY-MM-DD'),'짬뽕지존');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,8,1,3,3548746546532154,TO_TIMESTAMP('2023-10-26','YYYY-MM-DD'),'태이린한약국');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,8,1,1,6545134867986546,TO_TIMESTAMP('2023-10-26','YYYY-MM-DD'),'본죽앤비빔밥 역삼특허청점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,9,1,4,8036541223573435,TO_TIMESTAMP('2023-10-27','YYYY-MM-DD'),'드림디포 테헤란점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,10,1,2,9175686765416577,TO_TIMESTAMP('2023-10-30','YYYY-MM-DD'),'고속터미널');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,10,1,5,5321657876121335,TO_TIMESTAMP('2023-10-31','YYYY-MM-DD'),'성심당 대전역점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,13,1,4,2849683629587937,TO_TIMESTAMP('2023-10-31','YYYY-MM-DD'),'드림디포 테헤란점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,7,1,2,6937597937692749,TO_TIMESTAMP('2023-10-30','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,10,1,2,4927596725297956,TO_TIMESTAMP('2023-10-27','YYYY-MM-DD'),'카카오택시');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,9,1,2,5679855370071130,TO_TIMESTAMP('2023-10-13','YYYY-MM-DD'),'대한항공');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,13,1,3,4298209419451420,TO_TIMESTAMP('2023-10-05','YYYY-MM-DD'),'(주)마플');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,15,1,1,2297388266186908,TO_TIMESTAMP('2023-10-03','YYYY-MM-DD'),'CU강서구점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,1,1,5,3857514346884820,TO_TIMESTAMP('2023-10-04','YYYY-MM-DD'),'메가커피 역삼테헤란로점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,7,1,2,3274328747239890,TO_TIMESTAMP('2023-10-30','YYYY-MM-DD'),'고속터미널');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,9,1,4,1109053824376325,TO_TIMESTAMP('2023-10-16','YYYY-MM-DD'),'다이소 서초점');
INSERT INTO RECEIPT(NO, MEMBER_NO,RECEIPT_PROCESSING_STATE_NO, CATEGORY_NO, RECEIPT_SERIAL, PAYMENT_DATE, VENDOR) VALUES (SEQ_RECEIPT.NEXTVAL,12,1,5,9660899561849810,TO_TIMESTAMP('2023-10-10','YYYY-MM-DD'),'미래연구소');
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--RECEIPT_PROCESSING_HISTORY------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE RECEIPT_PROCESSING_HISTORY (
	NO	    NUMBER		NOT NULL PRIMARY KEY,
	MANAGER_NO	                NUMBER		NOT NULL,
	RECEIPT_NO	                NUMBER		NOT NULL,
	RECEIPT_PROCESSING_STATE_NO	NUMBER	    DEFAULT 1	    NOT NULL,
	PROCESS_DATE	            TIMESTAMP	DEFAULT SYSDATE	,
	NOTE	                    VARCHAR2(100)
);
COMMENT ON COLUMN RECEIPT_PROCESSING_HISTORY.RECEIPT_NO IS '시퀀스';
COMMENT ON COLUMN RECEIPT_PROCESSING_HISTORY.PROCESS_DATE IS '처리일자';
COMMENT ON COLUMN RECEIPT_PROCESSING_HISTORY.NOTE IS '비고';

ALTER TABLE RECEIPT_PROCESSING_HISTORY ADD CONSTRAINT FK_RECEIPT_PROCESSING_HISTORY_MANAGER FOREIGN KEY(MANAGER_NO) references MANAGER(NO);
ALTER TABLE RECEIPT_PROCESSING_HISTORY ADD CONSTRAINT FK_RECEIPT_PROCESSING_HISTORY_RECEIPT FOREIGN KEY(RECEIPT_NO) references RECEIPT(NO);
ALTER TABLE RECEIPT_PROCESSING_HISTORY ADD CONSTRAINT FK_RECEIPT_PROCESSING_HISTORY_RECEIPT_PROCESSING_STATE FOREIGN KEY(RECEIPT_PROCESSING_STATE_NO) references RECEIPT_PROCESSING_STATE(NO);

INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 1, 1, 4, TO_TIMESTAMP('2023-10-03 11:40:11','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 2, 4, TO_TIMESTAMP('2023-10-03 11:55:12','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 3, 4, TO_TIMESTAMP('2023-10-04 14:11:05','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 1, 4, 4, TO_TIMESTAMP('2023-10-04 15:01:05','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 5, 4, TO_TIMESTAMP('2023-10-06 10:43:51','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 6, 3, TO_TIMESTAMP('2023-10-07 13:11:03','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 7, 4, TO_TIMESTAMP('2023-10-08 14:21:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 8, 4, TO_TIMESTAMP('2023-10-08 14:55:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 1, 9, 4, TO_TIMESTAMP('2023-10-11 14:55:21','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 10, 4, TO_TIMESTAMP('2023-10-11 15:19:56','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 11, 4, TO_TIMESTAMP('2023-10-14 10:57:11','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 12, 4, TO_TIMESTAMP('2023-10-14 11:30:01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 13, 4, TO_TIMESTAMP('2023-10-15 14:05:01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 14, 4, TO_TIMESTAMP('2023-10-15 15:05:01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 1, 15, 4, TO_TIMESTAMP('2023-10-15 16:30:51','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY --반려 영수증
(NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)
VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 1, 16, 3, TO_TIMESTAMP('2023-10-18 17:30:01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 2, 17, 4, TO_TIMESTAMP('2023-10-19 16:11:51','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 18, 4, TO_TIMESTAMP('2023-10-22 16:11:51','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_PROCESSING_HISTORY (NO, MANAGER_NO, RECEIPT_NO, RECEIPT_PROCESSING_STATE_NO, PROCESS_DATE)VALUES (SEQ_RECEIPT_PROCESSING.NEXTVAL, 3, 19, 3, TO_TIMESTAMP('2023-10-22 17:05:51','YYYY-MM-DD HH24:MI:SS'));

------------------------------------------------------------------------------------------------------------------------------------------



--RECEIPT_APPLICATION_HISTORY------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE RECEIPT_APPLICATION_HISTORY(
   NO                     NUMBER          PRIMARY KEY NOT NULL
   , MEMBER_NO          NUMBER          NOT NULL
   , RECEIPT_NO          NUMBER          NOT NULL
   , APPLICATION_DATE       TIMESTAMP       DEFAULT SYSDATE   
   , CANCEL_DATE          TIMESTAMP       DEFAULT NULL
   , NOTE                 VARCHAR2(100)   DEFAULT NULL
);

ALTER TABLE RECEIPT_APPLICATION_HISTORY ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);
ALTER TABLE RECEIPT_APPLICATION_HISTORY ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_RECEIPT FOREIGN KEY(RECEIPT_NO) REFERENCES RECEIPT(NO);
COMMENT ON COLUMN RECEIPT_APPLICATION_HISTORY.NOTE IS '메모';

INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 1, 1, TO_TIMESTAMP('2023-10-02 14:35:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 1, 2, TO_TIMESTAMP('2023-10-02 14:37:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 2, 3, TO_TIMESTAMP('2023-10-03 09:16:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 2, 4, TO_TIMESTAMP('2023-10-04 11:46:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 3, 5, TO_TIMESTAMP('2023-10-05 17:33:04', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 3, 6, TO_TIMESTAMP('2023-10-06 09:10:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 4, 7, TO_TIMESTAMP('2023-10-07 11:14:29', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 4, 8, TO_TIMESTAMP('2023-10-07 14:43:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 5, 9, TO_TIMESTAMP('2023-10-10 09:37:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 5, 10, TO_TIMESTAMP('2023-10-10 14:11:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 11, 11, TO_TIMESTAMP('2023-10-13 12:31:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 11, 12, TO_TIMESTAMP('2023-10-13 15:29:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 12, 13, TO_TIMESTAMP('2023-10-14 10:26:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 12, 14, TO_TIMESTAMP('2023-10-14 11:15:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 15, TO_TIMESTAMP('2023-10-14 09:25:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 16, TO_TIMESTAMP('2023-10-17 11:08:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 14, 17, TO_TIMESTAMP('2023-10-18 13:55:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 14, 18, TO_TIMESTAMP('2023-10-21 10:04:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 15, 19, TO_TIMESTAMP('2023-10-21 14:57:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 15, 20, TO_TIMESTAMP('2023-10-24 15:23:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 6, 21, TO_TIMESTAMP('2023-10-24 14:44:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 6, 22, TO_TIMESTAMP('2023-10-24 10:45:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 23, TO_TIMESTAMP('2023-10-25 11:11:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 24, TO_TIMESTAMP('2023-10-25 13:15:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE) VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 8, 25, TO_TIMESTAMP('2023-10-26 17:25:31', 'YYYY-MM-DD HH24:MI:SS'));
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------





--CARD---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CARD (
	NO	NUMBER	        NOT             NULL		PRIMARY KEY,
	MEMBER_NO	        NUMBER	        NOT NULL,
	CARD_COMPANY_NO	    NUMBER	        NOT NULL,
	CARD_SERIAL	        VARCHAR2(30)	NOT NULL,
	CARD_PWD	        CHAR(4)	        NOT NULL,
    DEL_YN              CHAR(1)         DEFAULT 'N' NOT NULL 
);

INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 1, 1, '1111-1111-1111-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 2, 2, '2222-2222-2222-2222', '2000', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 3, 3, '9201-1852-3030-7281', '0123', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 4, 4, '7301-9102-1298-4720', '3210', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 5, 5, '3356-2918-8291-6651', '0000', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 6, 1, '1234-1234-1234-1234', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 7, 2, '2134-2134-2134-2134', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 8, 3, '1111-1111-1111-1112', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 9, 4, '1111-1111-1111-1234', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 10, 5, '1111-1111-1121-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 11, 1, '1123-1111-1111-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 12, 4, '1323-1111-1111-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 13, 3, '1111-1234-1111-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 14, 4, '1111-1111-1234-1111', '1234', 'N');
INSERT INTO CARD(NO, MEMBER_NO, CARD_COMPANY_NO, CARD_SERIAL, CARD_PWD, DEL_YN) VALUES(SEQ_CARD.NEXTVAL, 15, 5, '1333-1113-1113-1133', '1234', 'N');

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--NOTICE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE NOTICE (
   NO                   NUMBER         NOT NULL		PRIMARY KEY
   , MANAGER_NO       NUMBER         NOT NULL
   , TITLE            VARCHAR2(100)   NOT NULL
   , CONTENT           VARCHAR2(4000)   NOT NULL
   , ENROLL_DATE      TIMESTAMP       DEFAULT SYSDATE   NOT NULL 
    , DEL_YN           CHAR(1)           DEFAULT 'N'       NOT NULL
   , UPDATE_DATE       TIMESTAMP       DEFAULT SYSDATE   NULL
    , CLICK_NO         NUMBER         DEFAULT 0         NOT NULL
);

ALTER TABLE NOTICE MODIFY ENROLL_DATE TIMESTAMP DEFAULT SYSDATE;
ALTER TABLE NOTICE MODIFY DEL_YN CHAR DEFAULT 'N';
ALTER TABLE NOTICE MODIFY UPDATE_DATE TIMESTAMP DEFAULT SYSDATE;
ALTER TABLE NOTICE MODIFY CLICK_NO NUMBER DEFAULT 0;
COMMENT ON COLUMN NOTICE.ENROLL_DATE IS 'INSERT 때 고정';
COMMENT ON COLUMN NOTICE.UPDATE_DATE IS 'UPDATE 때마다 변경';


INSERT INTO NOTICE(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE, UPDATE_DATE) 
VALUES(SEQ_NOTICE.NEXTVAL, 2, '법인카드 발급', '법인카드 발급이 필요한 신입사원들은 3층 재무팀으로 직접 방문 바랍니다.  2023-10-04 오타 수정', TO_TIMESTAMP('2023-10-03', 'YYYY-MM-DD'), TO_TIMESTAMP('2023-10-04', 'YYYY-MM-DD'));
INSERT INTO NOTICE(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE)
VALUES(SEQ_NOTICE.NEXTVAL, 1, '시스템 업데이트(10월 8일)', '본인이 기입한 영수증이 아닌 영수증을 상신할 경우 상신 불가하도록 시스템이 업데이트 되었음을 알립니다.', TO_TIMESTAMP('2023-10-08', 'YYYY-MM-DD'));
INSERT INTO NOTICE(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE) 
VALUES(SEQ_NOTICE.NEXTVAL, 3, '카드사 관련 공지', '사내 법인카드 발급 은행에 카카오뱅크가 추가되었음을 알립니다.', TO_TIMESTAMP('2023-10-10', 'YYYY-MM-DD'));
INSERT INTO NOTICE(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE) 
VALUES(SEQ_NOTICE.NEXTVAL, 2, '영수증 기입 시 누락되는 물품이 없도록 각별히 주의 바람', '영수증 기입 시 물품이 누락되는 상황이 자주 발생하고 있습니다. 임직원 분들께서는 각별히 주의하여 기입해주시기 바랍니다.', TO_TIMESTAMP('2023-10-12', 'YYYY-MM-DD'));
INSERT INTO NOTICE(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE) 
VALUES(SEQ_NOTICE.NEXTVAL, 2, '시스템 업데이트(10월 15일)', '일대일 쪽지 기능이 추가되었습니다. 이후부터 프로그램 사용 관련 문의가 있을 경우 관리자에게 쪽지로 문의하여 주시기 바랍니다.', TO_TIMESTAMP('2023-10-15', 'YYYY-MM-DD'));
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--CARD_COMPANY-------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CARD_COMPANY (
   NO                       NUMBER           NOT NULL	PRIMARY KEY
   , CARD_COMPANY_NAME      VARCHAR2(50)     NOT NULL
);

COMMENT ON COLUMN CARD_COMPANY.NO IS '카드사코드';

INSERT INTO CARD_COMPANY(NO, CARD_COMPANY_NAME) VALUES(SEQ_CARD_COMPANY.NEXTVAL, '국민은행');
INSERT INTO CARD_COMPANY(NO, CARD_COMPANY_NAME) VALUES(SEQ_CARD_COMPANY.NEXTVAL, '신한은행');
INSERT INTO CARD_COMPANY(NO, CARD_COMPANY_NAME) VALUES(SEQ_CARD_COMPANY.NEXTVAL, '우리은행');
INSERT INTO CARD_COMPANY(NO, CARD_COMPANY_NAME) VALUES(SEQ_CARD_COMPANY.NEXTVAL, '카카오뱅크');
INSERT INTO CARD_COMPANY(NO, CARD_COMPANY_NAME) VALUES(SEQ_CARD_COMPANY.NEXTVAL, '새마을금고');
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



--FAQ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE FAQ (
   NO               NUMBER   NOT NULL	PRIMARY KEY
   , MANAGER_NO      NUMBER         NOT NULL
   , TITLE            VARCHAR2(100)   NOT NULL
   , CONTENT          VARCHAR2(4000)   NOT NULL
   , ENROLL_DATE      TIMESTAMP       DEFAULT SYSDATE     NOT NULL
   , DEL_YN           CHAR(1)              DEFAULT 'N'     NOT NULL
   , UPDATE_DATE      TIMESTAMP       DEFAULT SYSDATE     NULL
   , CLICK_NO         NUMBER         DEFAULT 0           NOT NULL
);

INSERT INTO FAQ(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE, UPDATE_DATE) 
VALUES(SEQ_FAQ.NEXTVAL, 1, '영수증 재상신 시 유의사항', '반려된 영수증을 재상신할 때는 반드시 비고 란에 재상신이라고 기입하고 상신해주시기 바랍니다.  2023-10-02 오타 수정', TO_TIMESTAMP('2023-10-01', 'YYYY-MM-DD'), TO_TIMESTAMP('2023-10-02', 'YYYY-MM-DD'));
INSERT INTO FAQ(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE) VALUES(SEQ_FAQ.NEXTVAL, 3, '법인카드 관련 안내사항', '법인카드는 직원 1명 당 1개 발급됩니다. 2개 이상의 법인카드를 사용할 수 없습니다.', TO_TIMESTAMP('2023-10-09', 'YYYY-MM-DD'));
INSERT INTO FAQ(NO, MANAGER_NO, TITLE, CONTENT, ENROLL_DATE) VALUES(SEQ_FAQ.NEXTVAL, 1, '쪽지', '문의사항이 있을 때에는 쪽지를 통해 관리자에게 1:1 문의가 가능합니다.', TO_TIMESTAMP('2023-10-16', 'YYYY-MM-DD'));


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--MESSSAGE-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE MESSAGE (
	NO	            NUMBER		    PRIMARY KEY     NOT NULL
	,FROM_ANY	    VARCHAR2(25)		            NOT NULL
    ,TO_ANY         VARCHAR2(25)                    NOT NULL
	,MESSAGE		VARCHAR2(4000)	
	,CREATE_AT	    TIMESTAMP       DEFAULT SYSDATE
	,READ		    VARCHAR2(10)	DEFAULT '안읽음' NOT NULL
);

COMMENT ON COLUMN MESSAGE.READ IS '읽음, 안읽음';

INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'twozero', '테스트메시지입니다.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'twozero', 'antifragile94', '테스트메시지입니다.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', '97aespa', '안녕하살법');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'silver92', '안녕하세요');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'mimi95', '김미현');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'itzycake', '잇지');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'feeling', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'slowdancing', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'akmuold', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'akmuyoung', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', '3seven', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'pinkblack', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'ivevictory', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'mjeans', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'fastforward', '안녕하세요.');
INSERT INTO MESSAGE(NO, FROM_ANY, TO_ANY, MESSAGE) VALUES (SEQ_MESSAGE.NEXTVAL, 'pwd486', 'hero10', '안녕하세요.');
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--PRODUCT------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE PRODUCT (
	NO	NUMBER		    NOT NULL PRIMARY KEY,
	RECEIPT_NO	NUMBER		    NOT NULL,
	PRODUCT	    VARCHAR2(50)    NOT NULL,
	UNIT_PRICE	NUMBER		    NOT NULL,
	EA	        NUMBER		    NOT NULL,
	TOTAL_PRICE	NUMBER		    NOT NULL
);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_RECEIPT FOREIGN KEY(RECEIPT_NO) references RECEIPT(NO);

INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 1, '불닭볶음면', 1600, 2, 3200);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 1, '스트링치즈', 800, 4, 3200);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 2, '볼펜', 500, 50, 25000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 3, '택시비', 18000, 1, 18000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 4, 'A코스', 200000, 5, 1000000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 4, '맥주', 5000, 5, 25000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 4, '소주', 5000, 7, 35000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 5, '버스비', 3000, 2, 6000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 6, '반창고', 2500, 5, 12500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 6, '마데카솔', 1500, 2, 3000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 7, '관리비', 200000, 2, 400000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 8, '삼각김밥', 1600, 2, 3200);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 9, '아메리카노', 2500, 5, 12500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 10, '택시비', 23000, 1, 23000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 11, '버스비', 3000, 3, 9000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 12, '육개장면', 1600, 1, 1600);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 12, '김밥', 1500, 2, 3000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 13, '택시비', 26500, 1, 26500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 14, '맥주', 5000, 5, 25000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 14, '념곱창', 20000, 5, 100000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 15, 'A4용지', 4000, 10, 40000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 16, '텐텐', 3500, 1, 3500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 17, '도시락', 4000, 1, 4000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 17, '생수', 1100, 1, 1100);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 18, '주유비', 70000, 1, 70000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 19, '택시비', 16700, 1, 16700);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 20, '클리어파일', 2000, 6, 12000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 21, '메가리카노', 3000, 5, 15000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 22, '식권', 7000, 3, 21000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 23, '박카스젤리', 2000, 6, 12000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 24, '돼지왕갈비', 15000, 4, 60000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 25, '지옥김치만두', 7000, 3, 21000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 26, '겔포스', 5000, 1, 5000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 27, '야채죽', 9500, 2, 19000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 28, 'A4용지2500매', 29000, 2, 58000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 29, '우등고속', 16600, 3, 49800);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 30, '튀김소보루', 1700, 35, 59500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 31, '스테이플러 심', 4000, 8, 32000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 32, '택시비', 26700, 1, 26700);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 33, '택시비', 30500, 1, 30500);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 34, '항공비', 120000, 2, 240000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 35, '단체티셔츠', 20000, 15, 300000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 36, '삼각김밥', 1600, 2, 3200);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 36, '불닭볶음면', 1600, 3, 4800);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 37, '메가리카노', 3000, 15, 45000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 38, '우등고속', 16600, 2, 33200);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 39, '지우개', 500, 10, 5000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 39, '자', 1000, 1, 1000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 39, '양면테이프', 2000, 10, 20000);
INSERT INTO PRODUCT(NO,RECEIPT_NO, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE) VALUES(SEQ_PRODUCT.NEXTVAL, 40, '교육비', 500000, 1, 500000);
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



--MEMO---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE MEMO (
	NO	NUMBER	NOT NULL,
	RECEIPT_NO	NUMBER	NOT NULL,
	NOTE	VARCHAR2(1000)	NOT NULL
);
ALTER TABLE MEMO ADD CONSTRAINT FK_MEMO_RECEIPT FOREIGN KEY(NO) references RECEIPT(NO);

INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 4, '회식진행');
INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 7, '사무실 정리를 위한 인력고용');
INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 14, '회식진행');
INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 30, '사원복지');
INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 37, '사원복지');
INSERT INTO MEMO(NO, RECEIPT_NO, NOTE) VALUES (SEQ_MEMO.NEXTVAL, 40, '강연초빙');
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
commit;
--
