--------------
-- 테이블 삭제
--------------
DROP TABLE RECEIPT_APPLICATION_HISTORY CASCADE CONSTRAINTS;

--------------
-- 시퀀스 삭제
--------------
DROP SEQUENCE SEQ_RECEIPT_APPLICATION;

--------------
-- 시퀀스 생성
--------------
CREATE SEQUENCE SEQ_RECEIPT_APPLICATION NOCYCLE NOCACHE;

--------------
-- 테이블 생성
--------------
-- RECEIPT_APPLICATION_HISTORY
CREATE TABLE RECEIPT_APPLICATION_HISTORY(
	NO                  	NUMBER		    PRIMARY KEY NOT NULL
	, MEMBER_NO		        NUMBER		    NOT NULL
	, RECEIPT_NO		    NUMBER		    NOT NULL
	, APPLICATION_DATE	    TIMESTAMP	    DEFAULT SYSDATE	NOT NULL
	, CANCEL_DATE		    TIMESTAMP       DEFAULT NULL
	, NOTE			        VARCHAR2(100)	DEFAULT NULL
);

ALTER TABLE RECEIPT_APPLICATION_HISTORY
ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_MEMBER
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);

ALTER TABLE RECEIPT_APPLICATION_HISTORY
ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_RECEIPT
FOREIGN KEY(RECEIPT_NO) REFERENCES RECEIPT(NO);

--------------
-- 더미 데이터
--------------
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 1, 1, TO_TIMESTAMP('2023-10-02 14:35:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 1, 2, TO_TIMESTAMP('2023-10-02 14:37:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 2, 3, TO_TIMESTAMP('2023-10-03 09:16:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 2, 4, TO_TIMESTAMP('2023-10-04 11:46:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 3, 5, TO_TIMESTAMP('2023-10-05 17:33:04', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 3, 6, TO_TIMESTAMP('2023-10-06 09:10:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 4, 7, TO_TIMESTAMP('2023-10-07 11:14:29', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 4, 8, TO_TIMESTAMP('2023-10-07 14:43:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 5, 9, TO_TIMESTAMP('2023-10-10 09:37:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 5, 10, TO_TIMESTAMP('2023-10-10 14:11:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 11, 11, TO_TIMESTAMP('2023-10-13 12:31:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 11, 12, TO_TIMESTAMP('2023-10-13 15:29:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 12, 13, TO_TIMESTAMP('2023-10-14 10:26:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 12, 14, TO_TIMESTAMP('2023-10-14 11:15:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 15, TO_TIMESTAMP('2023-10-14 09:25:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 16, TO_TIMESTAMP('2023-10-17 11:08:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 14, 17, TO_TIMESTAMP('2023-10-18 13:55:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 14, 18, TO_TIMESTAMP('2023-10-21 10:04:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 15, 19, TO_TIMESTAMP('2023-10-21 14:57:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 15, 20, TO_TIMESTAMP('2023-10-24 15:23:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 6, 21, TO_TIMESTAMP('2023-10-24 14:44:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 6, 22, TO_TIMESTAMP('2023-10-24 10:45:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 23, TO_TIMESTAMP('2023-10-25 11:11:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 24, TO_TIMESTAMP('2023-10-25 13:15:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 8, 25, TO_TIMESTAMP('2023-10-26 17:25:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 8, 26, TO_TIMESTAMP('2023-10-27 16:03:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 8, 27, TO_TIMESTAMP('2023-10-27 16:05:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 9, 28, TO_TIMESTAMP('2023-10-28 09:34:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 10, 29, TO_TIMESTAMP('2023-10-31 13:05:47', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 10, 30, TO_TIMESTAMP('2023-11-01 15:14:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 31, TO_TIMESTAMP('2023-11-01 11:40:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 32, TO_TIMESTAMP('2023-10-31 15:48:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 10, 33, TO_TIMESTAMP('2023-10-28 10:57:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 9, 34, TO_TIMESTAMP('2023-10-14 17:33:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 13, 35, TO_TIMESTAMP('2023-10-06 11:47:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 15, 36, TO_TIMESTAMP('2023-10-04 09:16:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 1, 37, TO_TIMESTAMP('2023-10-05 10:25:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 7, 38, TO_TIMESTAMP('2023-10-31 13:19:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 9, 39, TO_TIMESTAMP('2023-10-17 11:39:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RECEIPT_APPLICATION_HISTORY(NO, MEMBER_NO, RECEIPT_NO, APPLICATION_DATE)
VALUES(SEQ_RECEIPT_APPLICATION.NEXTVAL, 12, 40, TO_TIMESTAMP('2023-10-11 09:28:34', 'YYYY-MM-DD HH24:MI:SS'));