-- 내역 PRODUCT 테이블 INSERT
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 1, '불닭볶음면', 1600, 2, 3200);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 1, '스트링치즈', 800, 4, 3200);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 2, '볼펜', 500, 50, 25000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 3, '택시비', 18000, 1, 18000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 4, 'A코스', 200000, 5, 1000000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 4, '맥주', 5000, 5, 25000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 4, '소주', 5000, 7, 35000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 5, '버스비', 3000, 2, 6000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 6, '반창고', 2500, 5, 12500);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 6, '마데카솔', 1500, 5, 7500);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 7, '관리비', 200000, 2, 400000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 8, '삼각김밥', 1600, 2, 3200);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 9, '아메리카노', 2500, 5, 12500);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 10, '택시비', 23000, 1, 23000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 11, '버스비', 3000, 3, 9000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 12, '육개장면', 1600, 1, 1600);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 12, '김밥', 1500, 2, 3000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 13, '택시비', 26500, 1, 26500);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 14, '맥주', 5000, 5, 25000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 14, '양념곱창', 20000, 5, 100000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 15, 'A4용지', 4000, 10, 40000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 16, '텐텐', 3500, 1, 3500);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 17, '도시락', 4000, 1, 4000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 17, '생수', 1100, 1, 1100);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 18, '주유비', 70000, 1, 70000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 19, '택시비', 16700, 1, 16700);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 20, '클리어파일', 2000, 6, 12000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 21, '메가리카노', 3000, 5, 15000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 22, '식권', 7000, 3, 21000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 23, '박카스젤리', 2000, 6, 12000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 24, '돼지왕갈비', 15000, 4, 60000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 25, '지옥김치만두', 7000, 3, 21000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 26, '겔포스', 5000, 1, 5000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 27, '야채죽', 9500, 2, 19000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 28, 'A4용지2500매', 29000, 2, 58000);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 29, '우등고속', 16600, 3, 49800);
INSERT INTO PRODUCT(SEQ_PRODUCT, SEQ_RECEIPT, PRODUCT, UNIT_PRICE, EA, TOTAL_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, 30, '튀김소보루', 1700, 35, 59500);