-- 카테고리 CATEGORY INSERT문
INSERT INTO CATEGORY(SEQ_CATEGORY, CATEGORY_NAME)
VALUES(SEQ_CATEGORY.NEXTVAL, '식비');
INSERT INTO CATEGORY(SEQ_CATEGORY, CATEGORY_NAME)
VALUES(SEQ_CATEGORY.NEXTVAL, '교통비');
INSERT INTO CATEGORY(SEQ_CATEGORY, CATEGORY_NAME)
VALUES(SEQ_CATEGORY.NEXTVAL, '특별비');
INSERT INTO CATEGORY(SEQ_CATEGORY, CATEGORY_NAME)
VALUES(SEQ_CATEGORY.NEXTVAL, '비품');
INSERT INTO CATEGORY(SEQ_CATEGORY, CATEGORY_NAME)
VALUES(SEQ_CATEGORY.NEXTVAL, '기타');