--------------
-- 테이블 삭제
--------------
DROP TABLE RECEIPT_APPLICATION_HISTORY CASCADE CONSTRAINTS;

--------------
-- 시퀀스 삭제
--------------
DROP SEQUENCE SEQ_RECEIPT_APPLICATION;

--------------
-- 시퀀스 생성
--------------
CREATE SEQUENCE SEQ_RECEIPT_APPLICATION NOCYCLE NOCACHE;

--------------
-- 테이블 생성
--------------
-- RECEIPT_APPLICATION_HISTORY
CREATE TABLE RECEIPT_APPLICATION_HISTORY(
	SEQ_RECEIPT_APPLICATION	NUMBER		    PRIMARY KEY NOT NULL
	, SEQ_MEMBER		    NUMBER		    NOT NULL
	, SEQ_RECEIPT		    NUMBER		    NOT NULL
	, APPLICATION_DATE	    TIMESTAMP	    DEFAULT SYSDATE	NOT NULL
	, CANCEL_DATE		    TIMESTAMP       DEFAULT NULL
	, NOTE			        VARCHAR2(100)	DEFAULT NULL
);

ALTER TABLE RECEIPT_APPLICATION_HISTORY
ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_MEMBER
FOREIGN KEY(SEQ_MEMBER) REFERENCES MEMBER(SEQ_MEMBER);

ALTER TABLE RECEIPT_APPLICATION_HISTORY
ADD CONSTRAINT FK_RECEIPT_APPLICATION_HISTORY_RECEIPT
FOREIGN KEY(SEQ_RECEIPT) REFERENCES RECEIPT(SEQ_RECEIPT);
